language: python
python:
  - "2.7"
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $HOME/.cache/matplotlib
addons:
  apt:
    packages:
      - texlive-latex-base
install:
  - pip install -r requirements.txt
script:
  - cd analysis; make